### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by dorado89** [gturri/aXMLRPC#110]
This exception is showing when I try to connect to https://login.agni.lindenlab.com/cgi-bin/login.cgi
I tested the XMLRPC with https://xmlrpc.devzing.com/ and it is working as it should.
Here is my implementation of the library:
```
val uri = "https://login.agni.lindenlab.com/cgi-bin/login.cgi"
val xmlclient = XMLRPCClient(URL(uri), XMLRPCClient.FLAGS_SSL_IGNORE_INVALID_CERT)
        Thread({
            try {
                val response = xmlclient.call("login_to_simulator", items)
            }
            catch (ex: XMLRPCServerException) {
                Log.e("XMLRPCServerException: ",ex.message)
            }
            catch (ex: XMLRPCException) {
                Log.e("XMLRPCException: ",ex.message)
            }
            catch (ex:Exception) {
                Log.e("Exception: ",ex.message)
            }
        }).start()
```

**Comment by gturri** [comment]
Could you please:
- tell me the version of aXMLRPC you are using
- show me the stacktrace you have
- pass the `FLAGS_DEBUG`  (by turning line 2 of your code snippet to `val xmlclient = XMLRPCClient(URL(uri), XMLRPCClient.FLAGS_SSL_IGNORE_INVALID_CERT|FLAGS_DEBUG)` and show the relevant part that would be displayed on your console

**Comment by dorado89** [comment]
- aXMLRPC version : 1.8.0
- StackTrace:
```
W/System.err: de.timroes.axmlrpc.XMLRPCException: java.io.FileNotFoundException: https://login.agni.lindenlab.com/cgi-bin/login.cgi
        at de.timroes.axmlrpc.XMLRPCClient$Caller.call(XMLRPCClient.java:747)
W/System.err:     at de.timroes.axmlrpc.XMLRPCClient.call(XMLRPCClient.java:455)
W/System.err:     at com.dragongames.chalet.models.protocols.auth.Login$login$1.run(Login.kt:34)
        at java.lang.Thread.run(Thread.java:764)
W/System.err: Caused by: java.io.FileNotFoundException: https://login.agni.lindenlab.com/cgi-bin/login.cgi
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
W/System.err:     at de.timroes.axmlrpc.XMLRPCClient$Caller.call(XMLRPCClient.java:687)
    	... 3 more
```
- And FLAGS_DEBUG shows as a unresolved reference. looking at all the flags of XMLRPCClient, it doesn't show up as an option.

**Comment by dorado89** [comment]
- aXMLRPC version : 1.12.0
- StackTrace:
```
W/System.err: de.timroes.axmlrpc.XMLRPCException: java.io.FileNotFoundException: https://login.agni.lindenlab.com/cgi-bin/login.cgi
W/System.err:     at de.timroes.axmlrpc.XMLRPCClient$Caller.call(XMLRPCClient.java:756)
W/System.err:     at de.timroes.axmlrpc.XMLRPCClient.call(XMLRPCClient.java:467)
        at com.dragongames.chalet.models.protocols.auth.Login$login$1.run(Login.kt:34)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
W/System.err: Caused by: java.io.FileNotFoundException: https://login.agni.lindenlab.com/cgi-bin/login.cgi
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
        at de.timroes.axmlrpc.XMLRPCClient$Caller.call(XMLRPCClient.java:698)
W/System.err: 	... 3 
```
- FLAGS_DEBUG works in this vevrsion, but it only shows the xml that will to be send to the server:
```
I/System.out: <?xml version="1.0" encoding="UTF-8"?>
I/System.out: <methodCall>
    <methodName>login_to_simulator</methodName>
    <params>
    <param>
    <value>
    <struct>
I/System.out: <member>
    <name>viewer_digest</name>
    <value>
    <string>00000000-0000-0000-0000-000000000000</string>
    </value>
    </member>
    <member>
    <name>last</name>
I/System.out: <value>
    <string>tgh</string>
    </value>
    </member>
    <member>
I/System.out: <name>id0</name>
    <value>
    <string>fa434cb7-651c-4268-92d7-d612694120c7</string>
    </value>
    </member>
    <member>
I/System.out: <name>passwd</name>
    <value>
    <string>$1$ksdOxCNMbQXAEeVcfq5FLw==
    </string>
    </value>
    </member>
I/System.out: <member>
    <name>start</name>
    <value>
    <string>last</string>
    </value>
    </member>
I/System.out: <member>
    <name>channel</name>
    <value>
    <string>Chalet</string>
    </value>
I/System.out: </member>
    <member>
    <name>version</name>
    <value>
    <string>0.0.1</string>
I/System.out: </value>
    </member>
    <member>
    <name>first</name>
    <value>
    <string>tgh</string>
    </value>
    </member>
I/System.out: <member>
    <name>platform</name>
    <value>
    <string>Android</string>
    </value>
I/System.out: </member>
    <member>
    <name>mac</name>
    <value>
    <string>e7f385ee-f9d3-4aae-8732-420bc627ee9e</string>
I/System.out: </value>
    </member>
    <member>
    <name>agree_to_tos</name>
    <value>
    <string/>
I/System.out: </value>
    </member>
    <member>
    <name>read_critical</name>
    <value>
    <string/>
I/System.out: </value>
    </member>
    </struct>
    </value>
    </param>
    </params>
    </methodCall>
```

**Comment by gturri** [comment]
`curl -kI https://login.agni.lindenlab.com/cgi-bin/login.cgiW/System.err` tells me `HTTP/1.1 404 Not Found`. Could this error be due to a bad url?

**Comment by dorado89** [comment]
You have a typo, you should do ```curl -kI https://login.agni.lindenlab.com/cgi-bin/login.cgi``` not ```curl -kI https://login.agni.lindenlab.com/cgi-bin/login.cgiW/System.err```

**Comment by gturri** [comment]
Ah yes, sorry.
However this url gives me 403 error. Could the error comes from that?
Also, I'm a bit surprised to see references to `okhttp`  (and I have no clue what `com.dragongames.chalet` is): how is this possible with the code snippet you're showing? Do you have a particular setup?

**Comment by dorado89** [comment]
The server only accepts xml queries, anything else is forbidden, that is why the 403 error.  If you need to test connections, the server has a error message, if the query with method name ```login_to_simulator``` is empty or has incorrect parameters it will show the following response:
```
<?xml version="1.0"?>
<methodResponse>
    <params>
        <param>
            <value>
                <struct>
                    <member>
                        <name>message</name>
                        <value>
                            <string>Incorrect parameters.
If you feel this is an error, please contact
support@secondlife.com.</string>
                        </value>
                    </member>
                    <member>
                        <name>reason</name>
                        <value>
                            <string>data</string>
                        </value>
                    </member>
                    <member>
                        <name>login</name>
                        <value>
                            <string>false</string>
                        </value>
                    </member>
                </struct>
            </value>
        </param>
    </params>
</methodResponse>
```
As for ```okhttp```, is in the OS core and is the default HttpUrlConnection since Android 4.4 [Twitter link](https://twitter.com/JakeWharton/status/482563299511250944) .
The ```com.dragongames.chalet``` is my project name, it is only showing the method I am working in the stacktrace.

**Comment by gturri** [comment]
Thanks for this information.
So far I'm still not able to run a successful xmlrpc query with curl, which makes it pretty not convenient to investigate. More precisely I've tried running this query

  # simplified <struct> for readability
  curl -k -XPOST -d '<?xml version="1.0" encoding="UTF-8"?><methodCall><methodName>login_to_simulator</methodName><params><param><value><struct><member><name>viewer_digest</name><value><string>00000000-0000-0000-0000-000000000000</string></value></member></struct></value></param></params></methodCall>'  https://login.agni.lindenlab.com/cgi-bin/login.cgi

and I get a 400 error.

Could you provide me with a curl command that would succeed?

**Comment by gturri** [comment]
Thanks for this information.

Unfortunately I'm still not able to run a successful query with curl, which makes is pretty not convenient to investigate the issue with aXMLRPC. More precisely I've run this command (with simplified payload for readability)

`curl -k -XPOST -d '<?xml version="1.0" encoding="UTF-8"?><methodCall><methodName>login_to_simulator</methodName><params><param><value><struct><member><name>viewer_digest</name><value><string>00000000-0000-0000-0000-000000000000</string></value></member></struct></value></param></params></methodCall>'  https://login.agni.lindenlab.com/cgi-bin/login.cgi`

and it's giving me a 400 error:
`<html><head><title>400 Bad Request</title></head>
<body><h1>400 Bad Request</h1>
<p>Unexpected error processing XML-RPC request.</p>
</body></html>`

Am I missing a http header expected by the server? Could you provide me with a curl query which lead to the a valid response from the server?

**Comment by dorado89** [comment]
To be honest, I have never used cURL for XMLRPC queries. Tho as I see it, the cURL query you are doing atleast it is giving an response from the server. For my XMLRPC testing for this server, I am using ```https://xmlrpc.devzing.com/```, tho I don't know if that tool will work for you.

**Comment by dorado89** [comment]
Ok I fixed my implementation with a workaround. I did some testing and it seems that if you are ignoring or using custom certifications for a server that has a unknown certification it will throw a ```FileNotFound``` exception, my suspect on all this is ```HttpsURLConnection.sslSocketFactory```. My workaround was the implementation of a Network security configuration (NSC) and pass the website's certification. Hope if someone has this problem, might get this info useful.

**Comment by gturri** [comment]
Thanks for this information.
Could you please post here a snippet of code which shows your workaround (in case someone might need it in the future)?

**Comment by dorado89** [comment]
```
val xmlclient = XMLRPCClient(URL(uri))
```
The ``` XMLRPCClient.FLAGS_SSL_IGNORE_INVALID_CERT``` was triggering the error with this server. So I implemented Network Security Configuration (NSC) [Link](https://developer.android.com/training/articles/security-config).
So this are the snippets to implement the workaround for my problem:
- ```android:networkSecurityConfig="@xml/network_security_config"``` in the manifest file
- Configure a custom CA at ```res/xml/network_security_config.xml```
- And add the certification file at the raw folder ```res/raw/```

**Comment by gturri** [comment]
thanks for this information.
