### ISSUE TITLE
XMLRPCclient - CookieManager

### ISSUE THREAD

**Issue by florianewert** [gturri/aXMLRPC#137]
Hi, I have a quick question. If I use the XMLRPCclient, can I manually overwrite the previously set cookies?

best regards from germany 😎

**Comment by gturri** [comment]
Hi,
I think you should be able to do that if you call `CMLRPCClient.getCookies` and then edit the map that you get.
Don't hesitate to let me know if that work

(Btw, out of curiosity: why do you want to do this?)

**Comment by florianewert** [comment]
thanks, i will test it. 

I would resume an old session after starting a new session.

**Comment by florianewert** [comment]
It works. Thanks for your help ✌️
