### ISSUE TITLE
Message from Server-Error only in debug-mode in console

### ISSUE THREAD

**Issue by florianewert** [gturri/aXMLRPC#140]
Hi, 
when the server send an error, I get the message from Server-Error only in debug-mode and only in the console. How can i get the server-message directly as a String?

**Comment by gturri** [comment]
hi,

I'm afraid it's not possible out of the box.
I can think of one way to do it though: you could try to use your own transport (see doc at https://github.com/gturri/aXMLRPC/blob/master/README.md#using-an-arbitrary-transport ) so your code would perform the actual http query and retrieve the response.

Does that answer your question?
