### ISSUE TITLE
CDATA support

### ISSUE THREAD

**Issue by florianewert** [gturri/aXMLRPC#141]
Hi,
does aXMLRPC support the CDATA tag in a XML Response?
The client shows an error "Element must contain only text elements"

best regards

**Comment by gturri** [comment]
Hi,

I'm not sure if it's supposed to support this.

you say you tried it, could you please run it again with the debug flag on, and copy here the response you get from the server, as well as the stacktrace you have?

**Comment by florianewert** [comment]
Yes, thank you for your answer. I modified your code a bit. Change the following section in the XMLUtils class. This will allow the client to process CDATA tags as well: 

for(int i = 0; i < list.getLength(); i++) {
			n = list.item(i);

			// Skip comments inside the text tag.
			if(n.getNodeType() == Node.COMMENT_NODE) {
				continue;
			}

			if(n.getNodeType() != Node.TEXT_NODE) {
				throw new XMLRPCException("Element must contain text elements only.");
			}

			builder.append(n.getNodeValue());

		}

change to: 

for(int i = 0; i < list.getLength(); i++) {
			n = list.item(i);

			// Skip comments inside the text tag.
			if(n.getNodeType() == Node.COMMENT_NODE) {
				continue;
			}

			if(n.getNodeType() == Node.TEXT_NODE || n.getNodeType() == Node.CDATA_SECTION_NODE) {
            	builder.append(n.getNodeValue());
        	} else if (n.getNodeType() == Node.ELEMENT_NODE) {
            // check if the element has child nodes
            if (n.hasChildNodes()) {
                // Recursively call the function to handle child nodes
                String childText = getOnlyTextContent(n.getChildNodes());
                builder.append(childText);
            }
        } else {
            throw new XMLRPCException("Element must contain only text elements or CDATA sections.");
        }

**Comment by florianewert** [comment]
Hi, 
the example response from the server:

<?xml version="1.0" encoding="UTF-8"?><methodResponse>
    <fault>
        <value>
            <struct>
                <member>
                    <name>faultCode</name>
                    <value>
                        <int>-2147221502</int>
                    </value>
                </member>
                <member>
                    <name>faultString</name>
                    <value>
                        <string><![CDATA[
You are not authorized to show this content!
 : 
XMLRPCServer(3.0) - method@example.de
]]></string>
                    </value>
                </member>
            </struct>
        </value>
    </fault>
</methodResponse>

When the Server response with these answer, you can catch this errormessage as a string like:
catch (Exception e) {                     
                        showError(e.getMessage());                  
                    }

**Comment by gturri** [comment]
Thanks a lot!

I've just pushed a fix, inspired by the the patch you shared on your previous comment https://github.com/gturri/aXMLRPC/issues/141#issuecomment-1592514262

There is just something I don't understand in your patch: why does it care about the case `n.getNodeType() == Node.ELEMENT_NODE` (and then do a recursive call)? What am I missing? Are there use responses that my fix is still not able to deserialize correctly?
