### ISSUE TITLE
Separate connect/read timeouts, allow overrides per call

### ISSUE THREAD

**Issue by jeremybettis** [gturri/aXMLRPC#147]
I would like to have separate timeouts for connect and read, and allow at least the read timeout to be overridable on a per call basis.

I.e. Change the api to:

// Set the connect timeout
public void setConnectTimeout(Duration timeout);
// Set the read timeout
public void setReadTimeout(Duration timeout);
// Use the default read timeout from setReadTimeout.
public Object call(String method, Object... params) throws XMLRPCException;
// Use a specific read timeout for this call.
public Object call(String method, Duration timeout, Object... params) throws XMLRPCException

I don't know if that overload would actually work, since the Duration vs Object... could be ambiguous.

**Comment by gturri** [comment]
Thanks for this feature request.

I think those two commits above should do what you are looking for. (note that to avoid an issue with an ambiguous overload, I introduce the ad hoc name `callWithOverridenTimeout`.

Let me know if it seems it could work for you. If it does I'll merge those to `master` and push a new version to maven central.

**Comment by jeremybettis** [comment]
Yes, that looks perfect. Thank you.

**Comment by gturri** [comment]
Thanks for this feedback.

I've just merged those commits. I'll try to release a new version soon

**Comment by gturri** [comment]
It's available in aXMLRPC-1.15.0, which is now published.

**Comment by jeremybettis** [comment]
Oh, I should have read that pull request more closely. That new method can't be called, because it is in a private class.
