### ISSUE TITLE
No serializer found exception, XML escaping.

### ISSUE THREAD

**Issue by ghost** [gturri/aXMLRPC#31]
Hello. I use library for WordPress posting from Android app.
For about last week, i spontanly receiving this from client.call() method. I tried to reproduce bug, but it's realy random, and does not regard to connection speed or parameters in post body.

Can this be explained?

Upd:
This bug is in version 1.7.2.
After reverting to 1.7.0 all seems to be OK.
One more question for versions from 1.7.1 is, that earlier i did String escaping by myself due to necessary <img> tag in post body. Now, after escaping improvement, i cannot correctly transfer <img> tag - on server side i always getting &lt; and &gt; instead. So, i reverting to 1.7.0.

**Comment by gturri** [comment]
Closing because it's probably fixed by https://github.com/gturri/aXMLRPC/commit/5c8d8dfdfe559cccb3e0a06b707b223c61d22339 ; and this issue is almost 4 years old anyway so probably not relevant anymore.
