### ISSUE TITLE
Error with empty element tag

### ISSUE THREAD

**Issue by Remie-l** [gturri/aXMLRPC#33]
I send request to server, and check it with Wireshark - the response is coming good. But, logcat return error:
de.timroes.axmlrpc.XMLRPCException: Error getting result from server.

I analyse the response from server, and found that there is an empty element tag - "value"

```
<member><name>datepost</name><value /></member>
```

Everything else is OK.

Can it be solved? Thanks!

**Comment by gturri** [comment]
Closing because empty value doesn't seems compliant with the spec anyway
