### ISSUE TITLE
Parse xmlrpc direct to Json with SAX

### ISSUE THREAD

**Issue by autonomous1** [gturri/aXMLRPC#45]
Hello,

I wrote a parser handler for aXMLRPC that generates a json object model directly from xmlrpc via sax parsing with no intermediate data structures generated during processing. It produces a json object model equivalent to importing an aXMLRPC object model into gson.

I noted that a few projects using aXMLRPC convert the output to json, and this scenario requires multiple object models to be constructed to obtain a json object model. On mobile devices where multi-megabyte datasets are generated, memory limitations cause frequent garbage collection tasks to occur, as well as there being a lot of processing involved.

I also added junit test cases that process xmlrpc datasets stored as text files.

Additional libraries needed are com.google.gson and org.xml.sax. Let me know if you wish to include this code in the project.

**Comment by juddgaddie** [comment]
Is this code available anywhere to review ?

**Comment by autonomous1** [comment]
It is not posted anywhere or on github but I can send you the zip file for
the parser . I must say that the method of parsing direct to json via sax
offers a substantial performance increase over parsing into dom and
traversing the dom tree.

**Comment by juddgaddie** [comment]
Why do you want to construct a JSON object model from XML, why not just build up a POJO directly ?

I'm not sure if it will help with performance unless the response is significantly large as aXMLRPC makes a new TCP connection for every api call. I find this slows down multiple api calls significantly.

Happy to look at the code if you send it my way.

**Comment by autonomous1** [comment]
Because the xmlrpc data is forwarded to javascript which consumes the json
object.

Since the resulting json objects could be quite large, in some cases
several megabytes, parsing directly to json or pojo saves memory and
processing time. The sax parser could be easily modified to create a pojo.

**Comment by juddgaddie** [comment]
That sounds excellent just not required for my use case.

Why not just fork aXMLRPC on Github and commit your changes?

**Comment by autonomous1** [comment]
Sure, I could fork aXMLRPC, no problem!

**Comment by gturri** [comment]
@autonomous1 , I'm discovering this issue just right now because I wasn't the maintainer of aXMLRPC when you opened it a year ago.
If you commit your feature on a fork on Github, what about submitting a pull request, so that we might potentially include it here?

**Comment by gturri** [comment]
No news for more than a year, and the patch seems to be nowhere to be found. Closing because there's hence not much that can be done about this issue.
