### ISSUE TITLE
Application being rejected

### ISSUE THREAD

**Issue by Viish** [gturri/aXMLRPC#61]
Hi,

When trying to publish my app, I get this message:
Beginning May 17, 2016, Google Play will block publishing of any new apps or updates containing the unsafe implementation of the interface X509TrustManager.

Can you do something about it ?

Best regards.

**Comment by gturri** [comment]
Hi,

Thanks for the bug report. I think it shouldn't be too hard to fix, but it will likely result in removing a feature (the flag FLAGS_SSL_INGORE_INVALID_CERT).
In order to minimize the negative impact it might have, I would be grateful if you can give me more info on the exact cause of the issue (for instance a link to a doc which describes the scope of this limitation)

**Comment by Viish** [comment]
Maybe this will be helpful: https://developer.android.com/training/articles/security-ssl.html#UnknownCa

**Comment by Viish** [comment]
This stackoverflow has an accepted answer for the same issue as well: http://stackoverflow.com/questions/35530558/how-to-fix-unsafe-implementation-of-x509trustmanager-in-android-app

**Comment by gturri** [comment]
Thanks for those pointers.

I  pushed what should be a fix on the branch `fix61` (https://github.com/gturri/aXMLRPC/commits/fix61): https://github.com/gturri/aXMLRPC/commit/f0e4e8de1b0f2e544a27fdb08b6ebb3a6993161a

Before I push it on `master`, can you check that it indeed fixes the issue?

**Comment by Viish** [comment]
Hi,

Thanks for the branch but removing the features ins't really a fix. 
Anyway I do believe however that it will allow the app to be published (but I can't try it right now).
Do you have plan to get the feature working somehow ?

Cheers.

**Comment by gturri** [comment]
I adapted the readme (see the commit) to explain how one could still bypass invalid certificates.
It will be less convenient, but as far as I understand the issue, it's not possible to do better

**Comment by Viish** [comment]
What you put in the README is to use the X509TrustManager which is the cause of the app being rejected. I believe the "solution" in the README will cause any app using this to be rejected as well.

**Comment by gturri** [comment]
Indeed.
As far as I understand, with this constraint from Google Play, it's not possible anymore to have an application that could allow any invalid certificate.

**Comment by gturri** [comment]
@viish , any chance you could validate that this commit indeed fixes this issue? Shall I merge it into `master`?

**Comment by gturri** [comment]
Closing the issue since OP didn't reply for more than 6 months
(feel free to re-open it if needed)
