### ISSUE TITLE
Tuple Serialization & DeSerialization 

### ISSUE THREAD

**Issue by ashishoc** [gturri/aXMLRPC#65]
Hi,

I'm trying to pass tuple as variable but it is throwing serialization error. Can you fix this ? Please help I'm Stuck at middle of development. 

> class Pair<A,B> {
>     A a;
>     B b;
>     public Pair( A a, B b ) {
>         this.a = a;
>         this.b = b;
>     } 
> }

http://stackoverflow.com/questions/7733673/triples-in-java

I have to pass object (python tupple) like      **[(4, 3)]**

how can I achieve this with library?

Thanks

**Comment by gturri** [comment]
Hi,

what does your code look like, and what is the exception (and stacktrace) you have?

**Comment by gturri** [comment]
Closing since the OP didn't reply for more than 6 months
