### ISSUE TITLE
How to want quert with aXmLRPC from get limit data??

### ISSUE THREAD

**Issue by kalvian1060** [gturri/aXMLRPC#67]

**Comment by kalvian1060** [comment]
this my query
   Map fields = new HashMap() {{
            Arrays.asList(
                    Arrays.asList(Arrays.asList(put("fields", Arrays. asList (
                            "id",
                            "name",
                            "image_medium",
                            "company_id",
                            "barcode_nomenclature_id",
                            "stock_location_id",
                            "pricelist_id",
                            "time_format"
                            )),
                            put("offset",10),
                            put("limit",5)))

            );

        }};

**Comment by kalvian1060** [comment]
this for query..
downloadData = odoo.search_read(listener, Api.DB,mUid, Api.PASS, "pos.config", conditions, fields);

**Comment by gturri** [comment]
Hi,

I'm not sure I completely understand the question.
(As far as I can tell, it looks more like a question you'd want to ask to odoo guys)

**Comment by kalvian1060** [comment]
sorry about that ,,
my language is very bad

this question about how to use 
`asList((Object[])models.execute("execute_kw", asList(
    db, uid, password,
    "res.partner", "search",
    asList(asList(
        asList("is_company", "=", true),
        asList("customer", "=", true))),
    new HashMap() {{ put("offset", 10); put("limit", 5); }}
)));`

in aXMLRPC...??

**Comment by kalvian1060** [comment]
this document about API odoo...
https://www.odoo.com/documentation/9.0/api_integration.html

**Comment by gturri** [comment]
Well, xmlrpc is a standard which explains how a client and a server should communicate ([see the spec](http://xmlrpc.scripting.com/)).
And aXMLRPC is just an xmlrpc implementation which make it easy to make such queries and to retrieve the replies.

I'm afraid your question is about how to use code that comes from the  odoo documentation. I don't know this code. I don't know what the `models` class is. I don't know what its `execute` method is supposed to do.
I believe you'd better ask odoo guys

**Comment by kalvian1060** [comment]
thanys guys
