### ISSUE TITLE
How to delay request for xmlrpc??

### ISSUE THREAD

**Issue by kalvian1060** [gturri/aXMLRPC#69]
how to set 5 minute request aXMLrpc if networks is slow??

**Comment by kalvian1060** [comment]
thanks

**Comment by gturri** [comment]
If the network is slow, you may increase the timeout using the method `XMLRPCClient.setTimeout` (https://github.com/gturri/aXMLRPC/blob/master/src/main/java/de/timroes/axmlrpc/XMLRPCClient.java#L303)

**Comment by kalvian1060** [comment]
thanks @gturri  for respond...
so what the unit time if i set

`client.setTimeOut(5000)`

**Comment by gturri** [comment]
According to the javadoc (https://github.com/gturri/aXMLRPC/blob/master/src/main/java/de/timroes/axmlrpc/XMLRPCClient.java#L301) it's in seconds
