### ISSUE TITLE
Latest version of the dependency

### ISSUE THREAD

**Issue by aj019** [gturri/aXMLRPC#71]
What is the latest version of the dependency used in this project ?

**Comment by gturri** [comment]
Hi,

all this info is in the [pom.xml](https://github.com/gturri/aXMLRPC/blob/master/pom.xml).

That is:
* The current dev version of aXMLRPC is 1.10.0-SNAPSHOT (the latest stable is [1.9.0](http://search.maven.org/#search%7Cga%7C1%7Caxmlrpc))
* besides dependencies needed for tests, it only uses jISO8601, version 0.2 (cf line 40-44 of the pom.xml), which doesn 't have any transitive [dependency](http://search.maven.org/#artifactdetails%7Cfr.turri%7CjISO8601%7C0.2%7Cjar)

If you want to know more about pom.xml and maven, you might want to read
* an introduction on wikipedia: https://en.wikipedia.org/wiki/Apache_Maven
* the documentation on the maven website: https://maven.apache.org/

I hope it helps. Feel free to re-open the issue if you have additional questions.
