### ISSUE TITLE
XMLRPCException Error getting result from server.

### ISSUE THREAD

**Issue by sashas777** [gturri/aXMLRPC#77]
Hi

I  couldn't find out what can be issue:

06-07 03:32:47.476 24314-24645/com.magapp.main E/Sashas: RequestArrayTask::doInBackground:XMLRPCException Error getting result from server.
06-07 03:32:47.477 24314-24645/com.magapp.main W/System.err: de.timroes.axmlrpc.XMLRPCException: Error getting result from server.
06-07 03:32:47.479 24314-24645/com.magapp.main W/System.err:     at de.timroes.axmlrpc.ResponseParser.parse(ResponseParser.java:87)
06-07 03:32:47.480 24314-24645/com.magapp.main W/System.err:     at de.timroes.axmlrpc.XMLRPCClient$Caller.call(XMLRPCClient.java:747)
        at de.timroes.axmlrpc.XMLRPCClient.call(XMLRPCClient.java:467)
06-07 03:32:47.481 24314-24645/com.magapp.main W/System.err:     at com.magapp.connect.RequestArrayTask.doInBackground(RequestArrayTask.java:70)
        at com.magapp.connect.RequestArrayTask.doInBackground(RequestArrayTask.java:28)
06-07 03:32:47.482 24314-24645/com.magapp.main W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-07 03:32:47.483 24314-24645/com.magapp.main W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
06-07 03:32:47.484 24314-24645/com.magapp.main W/System.err:     at java.lang.Thread.run(Thread.java:764)
06-07 03:32:47.490 24314-24645/com.magapp.main W/System.err: Caused by: de.timroes.axmlrpc.XMLRPCException: No deserializer found for type 'nil'.
        at de.timroes.axmlrpc.serializer.SerializerHandler.deserialize(SerializerHandler.java:126)
06-07 03:32:47.491 24314-24645/com.magapp.main W/System.err:     at de.timroes.axmlrpc.serializer.StructSerializer.deserialize(StructSerializer.java:71)
        at de.timroes.axmlrpc.serializer.SerializerHandler.deserialize(SerializerHandler.java:129)
06-07 03:32:47.492 24314-24645/com.magapp.main W/System.err:     at de.timroes.axmlrpc.serializer.ArraySerializer.deserialize(ArraySerializer.java:53)
        at de.timroes.axmlrpc.serializer.SerializerHandler.deserialize(SerializerHandler.java:129)
06-07 03:32:47.493 24314-24645/com.magapp.main W/System.err:     at de.timroes.axmlrpc.ResponseParser.getReturnValueFromElement(ResponseParser.java:118)
        at de.timroes.axmlrpc.ResponseParser.parse(ResponseParser.java:71)
    	... 10 more
06-07 03:32:47.879 24314-24314/com.magapp.main E/Sashas: RequestArrayTask::doInBackground:XMLRPCException null

The webserver uses nginx.  Can you point me how to get detailed log, please?
I use Android Studio and used gradle if it helps.

**Comment by gturri** [comment]
It seems the server reply can't be parsed. You can build the `XMLRPCClient` with the `FLAGS_DEBUG`: it will display the server reply on the console so it will be easier to understand what is going on.

**Comment by sashas777** [comment]
@gturri 
I tried to use FLAFS_DEBUG but in this case, I getting XML response at the console.  The response is big but I can see that it has <params><param>  and data type is <array> 

Is there a way to find out what specifically is wrong?

**Comment by gturri** [comment]
According to the stacktrace there's an unexpected `nil` at some point.

If you have a big reply from the server you may try to make it smaller and smaller, to pinpoint the part which is the cause of the issue. (For instance replace your actual server with a stub that will return a hard-coded  reply that you could edit, or write a test using [wiremock](http://wiremock.org/))

**Comment by sashas777** [comment]
@gturri 

Seems that FLAG_NIL hepled.

Thanks you
