### ISSUE TITLE
return hashmap problem

### ISSUE THREAD

**Issue by naser2884** [gturri/aXMLRPC#80]
Hi

i have connected correctly to jetty on my server nia axmlrpc, when i return integer number its ok, but i want return HashMap<String, Object[]> i get "XMLRPCException: Error getting result from server."

can i return this ? or return arraylist<string> only with 20 values ?

pls get me good solution.

thanks

**Comment by gturri** [comment]
Hi,

AFAIU `HashMap<String, Object[]>` isn't a type supported by the xmlrpc protocol and hence by this library.

You may want to have a look at 
* the xmlrpc specification http://xmlrpc.scripting.com/spec.html to find out the types supported by this protocol
* the documentation of aXMLRPC to find out how it maps to java types: https://github.com/gturri/aXMLRPC#the-data-types

**Comment by naser2884** [comment]
Ok , what about "array	=> Object[]" ?

i test to return Object[] same the problem ?

pls give me way to return multi-values from server 

thanks

**Comment by gturri** [comment]
An xmlrpc `struct` will be mapped to a `Map<String,Object>`.
An xmlrpc `array` will be mapped to `Object[]`

You might want to read the xmlrpc [specification](http://xmlrpc.scripting.com/spec.html) to see how this data should be serialized by the server.

**Comment by naser2884** [comment]
many thanks @gturri , but why u dont need give me example pls i am new 

i am return Object[] from server to client but same problem, 


please please please tell me how can i return array of string from server 

i waiting u

**Comment by naser2884** [comment]
@gturri i am using xmlrpc on java app swing, and i am return hashmap and arraylist without problem, but here i dont know how can i do it.

please tell me how return arraylist from server and receive it in client with small code ,
please please please

**Comment by gturri** [comment]
I can't give you more details because I don't know what the server is sending. I don't know swing, I don't know the code you're using on the server, I don't know if there are error in your server log.
You could try to build the instance of `XMLRPCClient` with the flag `FLAGS_DEBUG`: it will give you more information about what went wrong

**Comment by naser2884** [comment]
@gturri ok i know the error

XMLRPCException: net.ddns.nasserpi.loginapp.XMLRPCException: The Content-Type of the response must be text/xml.

what the best solution ?
