### ISSUE TITLE
Mapping nested complex properties

### ISSUE THREAD

**Issue by rbiq** [gturri/aXMLRPC#89]
```
class Show {
   String showName
   Integer showId
   List<ShowTime> showTimes 
}

class ShowTime {
   Integer showTimeId
   DateTime startDate,
   List<ShowPrice> prices
}

class ShowPrice {
    Integer priceId,
    Decimal minPrice,
     Decimal maxPrice
}
```
With the above model in place, I'm trying to call 
`Show show = (Show) client.call('getShow', apiKey)`

this will work and map the Show primitive properties correctly except showTimes. For showTimes which is a complex property its returning a HashMap. Is this default behavior or am I missing something? Likewise prices will also get mapped as object[]. How do I resolve this issue? Can you please offer any insight?

**Comment by gturri** [comment]
Hi,
My understanding is that complex types aren't supported by [the xmlrpc spec](http://xmlrpc.scripting.com/spec.html). Also, aXMLRPC has no knowledge about your classes so I'm not sure there would be an easy way to return them. I'm afraid you have to write a method to convert the returned Object into the ones you're expecting. See for instance how this client does it: https://github.com/gturri/dokuJClient/blob/master/src/main/java/dw/xmlrpc/Locker.java#L35
